#!/bin/sh -e
. t/common.sh
interactive

printf '%s\n' > file \
	"${HEAD} ours" \
	same \
	ours \
	"${PARENT} base" \
	same \
	base \
	"${TAIL}" \
	same \
	theirs \
	"${END} theirs"

printf '%s\n' > file.expected \
	same \
	ours

printf '%s' h > input
normal --merge --symmetric --remove-base --reduce --interactive file 8<input 9>output
test -s output
