#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	same \
	new \
	"${PARENT} base" \
	same \
	old \
	"${TAIL}" \
	same \
	new \
	"${END} theirs"

printf '%s\n' > file.expected \
	same \
	"${HEAD} ours" \
	new \
	"${PARENT} base" \
	old \
	"${TAIL}" \
	new \
	"${END} theirs"

conflict --symmetric --no-symmetric --no-symmetric file

also_interactive r
