#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	same \
	new \
	"${PARENT} base" \
	same \
	old \
	"${TAIL}" \
	same \
	new \
	"${END} theirs"

printf '%s\n' > file.expected \
	same \
	new

normal --symmetric --symmetric --no-reduce file

also_interactive y
