#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} 1" \
	old-1 \
	"${PARENT} 1" \
	old-1 \
	"${TAIL} 1" \
	new-1 \
	"${END} 1" \
	"${HEAD} 2" \
	new-2 \
	"${PARENT} 2" \
	old-2 \
	"${TAIL} 2" \
	new-2 \
	"${END} 2"

printf '%s\n' > file.expected \
	new-1 \
	new-2

normal --merge --symmetric --no-reduce file

also_interactive my
