#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	ours \
	"${PARENT} base" \
	base \
	"${TAIL}" \
	theirs \
	"${END} theirs"

printf '%s\n' > file.expected \
	theirs

normal --remove-base --select-tail --reduce file

also_interactive t
