#!/bin/sh -e
. t/common.sh

printf '%s\n' text > file
cp -- file file.expected

all_permutations () {
	if test $# = 2; then
		error "$1" "$2" file
		error "$2" "$1" file
	elif test $# = 3; then
		error "$1" "$2" "$3" file
		error "$1" "$3" "$2" file
		error "$2" "$1" "$3" file
		error "$2" "$3" "$1" file
		error "$3" "$1" "$2" file
		error "$3" "$2" "$1" file
	elif test $# = 4; then
		error "$1" "$2" "$3" "$4" file
		error "$1" "$2" "$4" "$3" file
		error "$1" "$3" "$2" "$4" file
		error "$1" "$3" "$4" "$2" file
		error "$1" "$4" "$2" "$3" file
		error "$1" "$4" "$3" "$2" file
		error "$2" "$1" "$3" "$4" file
		error "$2" "$1" "$4" "$3" file
		error "$2" "$3" "$1" "$4" file
		error "$2" "$3" "$4" "$1" file
		error "$2" "$4" "$1" "$3" file
		error "$2" "$4" "$3" "$1" file
		error "$3" "$1" "$2" "$4" file
		error "$3" "$1" "$4" "$2" file
		error "$3" "$2" "$1" "$4" file
		error "$3" "$2" "$4" "$1" file
		error "$3" "$4" "$1" "$2" file
		error "$3" "$4" "$2" "$1" file
		error "$4" "$1" "$2" "$3" file
		error "$4" "$1" "$3" "$2" file
		error "$4" "$2" "$1" "$3" file
		error "$4" "$2" "$3" "$1" file
		error "$4" "$3" "$1" "$2" file
		error "$4" "$3" "$2" "$1" file
	else
		printf 'Error in test case: all_permutations was given %s arguments\n' "$#" >&2
		exit 99;
	fi
}

all_permutations --select-head --select-tail
all_permutations --merge --select-head
all_permutations --merge --select-tail
all_permutations --merge --select-head --select-tail
all_permutations --symmetric --select-head
all_permutations --symmetric --select-tail
all_permutations --symmetric --select-head --select-tail
all_permutations --merge --symmetric --select-head
all_permutations --merge --symmetric --select-tail
all_permutations --merge --symmetric --select-head --select-tail

error --unknown-option file
error '-$' file
