#!/bin/sh -e
. t/common.sh

set_conflict_marker_size 3 file

printf '%s\n' > file \
	"${HEAD} ours" \
	same \
	"${TAIL}" \
	same \
	"${END} theirs'"

printf '%s\n' > file.expected \
	same

normal file

also_interactive r
