#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} 1" \
	different \
	"${PARENT} 2" \
	same \
	"${PARENT} 3" \
	same \
	"${TAIL}" \
	same \
	"${END} 4"

printf '%s\n' > file.expected \
	different

normal --merge --no-reduce file

also_interactive m
