#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} a" \
	different \
	"${PARENT} b" \
	same \
	"${TAIL}" \
	same \
	"${END} c"

printf '%s\n' > file.expected \
	different

normal --merge --no-reduce file

also_interactive m
