#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	same \
	ours \
	"${PARENT} base" \
	same \
	base \
	"${TAIL}" \
	same \
	theirs \
	"${END} theirs"

printf '%s\n' > file.expected \
	same \
	"${HEAD} ours" \
	ours \
	"${PARENT} base" \
	base \
	"${TAIL}" \
	theirs \
	"${END} theirs"

conflict --no-select-tail file

also_interactive rr
