#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	ours \
	"${PARENT} base" \
	base \
	"${TAIL}" \
	theirs \
	"${END} theirs"

printf '%s\n' > file.expected \
	ours

normal --no-select-head --select-head --no-reduce file

also_interactive h
