#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	ours \
	"${PARENT} base" \
	base \
	"${TAIL}" \
	theirs \
	"${END} theirs"

cp -- file file.expected

conflict --select-head --no-select-head --no-reduce file

also_interactive s
