#!/bin/sh -e
. t/common.sh

interactive

printf '%s\n' > file \
	"${HEAD} ours" \
	ours \
	"${PARENT} base" \
	base \
	"${TAIL}" \
	theirs \
	"${END} theirs"

cp -- file file.expected

printf '%s' q > input

conflict --interactive --no-interactive --no-reduce file 8<input 9>output
