#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} 1" \
	head-common-first \
	head-common-second \
	branch-1-first-a \
	branch-1-first-b \
	middle-common-first \
	middle-common-second \
	branch-1-second-a \
	branch-1-second-b \
	tail-common-first \
	tail-common-second \
	"${PARENT} 2" \
	head-common-first \
	head-common-second \
	branch-2-first-a \
	branch-2-first-b \
	middle-common-first \
	middle-common-second \
	branch-2-second-a \
	branch-2-second-b \
	tail-common-first \
	tail-common-second \
	"${PARENT} 3" \
	head-common-first \
	head-common-second \
	branch-3-first-a \
	branch-3-first-b \
	middle-common-first \
	middle-common-second \
	branch-3-second-a \
	branch-3-second-b \
	tail-common-first \
	tail-common-second \
	"${TAIL} 4" \
	head-common-first \
	head-common-second \
	branch-4-first-a \
	branch-4-first-b \
	middle-common-first \
	middle-common-second \
	branch-4-second-a \
	branch-4-second-b \
	tail-common-first \
	tail-common-second \
	"${END} 4"

cp -- file file.expected

conflict --no-reduce file

also_interactive s
