#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} 1" \
	common-first \
	common-second \
	common-third \
	"${PARENT} 2" \
	common-first \
	common-second \
	common-third \
	"${PARENT} 3" \
	common-first \
	common-second \
	common-third \
	"${PARENT} 4" \
	common-first \
	common-second \
	common-third \
	"${TAIL} 5" \
	common-first \
	common-second \
	common-third \
	"${END} 5"

printf '%s\n' > file.expected \
	common-first \
	common-second \
	common-third

normal --reduce file

also_interactive r
