#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	common \
	"${PARENT} base" \
	"${TAIL}" \
	common \
	"${END} theirs"

cp -- file file.expected

conflict --reduce file

also_interactive r
