#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} 1" \
	branch-1-before-first \
	branch-1-before-second \
	middle-common-first \
	middle-common-second \
	branch-1-after-first \
	branch-1-after-second \
	"${PARENT} 2" \
	branch-2-before-first \
	branch-2-before-second \
	middle-common-first \
	middle-common-second \
	branch-2-after-first \
	branch-2-after-second \
	"${TAIL} 3" \
	branch-3-before-first \
	branch-3-before-second \
	middle-common-first \
	middle-common-second \
	branch-3-after-first \
	branch-3-after-second \
	"${END} 3"

printf '%s\n' > file.expected \
	"${HEAD} 1" \
	branch-1-before-first \
	branch-1-before-second \
	"${PARENT} 2" \
	branch-2-before-first \
	branch-2-before-second \
	"${TAIL} 3" \
	branch-3-before-first \
	branch-3-before-second \
	"${END} 3" \
	middle-common-first \
	middle-common-second \
	"${HEAD} 1" \
	branch-1-after-first \
	branch-1-after-second \
	"${PARENT} 2" \
	branch-2-after-first \
	branch-2-after-second \
	"${TAIL} 3" \
	branch-3-after-first \
	branch-3-after-second \
	"${END} 3"

conflict --reduce file

also_interactive rrr
