#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	ours \
	"${PARENT} base" \
	base \
	"${TAIL}" \
	theirs \
	"${END} theirs"

printf '%s\n' > file.expected \
	"${HEAD} ours" \
	ours \
	"${TAIL}" \
	theirs \
	"${END} theirs"

conflict --remove-base --no-reduce file

also_interactive bb
