#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} head" \
	head \
	"${PARENT} 2" \
	second \
	"${PARENT} 3" \
	third \
	"${TAIL}" \
	tail \
	"${END} tail"

cp -- file file.expected

conflict --remove-base --no-reduce file

also_interactive b
