#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} first" \
	first-head \
	"${TAIL}" \
	first-tail \
	"${END}" \
	between \
	"${HEAD} second" \
	second-head \
	"${PARENT} middle" \
	second-middle \
	"${TAIL}" \
	second-tail \
	"${END}" \
	after

printf '%s\n' > file.expected \
	first-head \
	between \
	second-head \
	after

normal --select-head --no-reduce file

also_interactive hh
