#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD}" \
	ours \
	"${PARENT}" \
	"${TAIL}" \
	theirs \
	"${END}"

printf '%s\n' > file.expected \
	ours

normal --select-head --no-reduce file

also_interactive h
