#!/bin/sh -e
. t/common.sh

printf '%s\n' > first \
	"${HEAD} first" \
	first-head \
	"${TAIL}" \
	first-tail \
	"${END}"

printf '%s\n' > first.expected \
	first-head

printf '%s\n' > second \
	before \
	"${HEAD} second" \
	second-head \
	"${PARENT} middle" \
	second-middle \
	"${TAIL}" \
	second-tail \
	"${END}"

printf '%s\n' > second.expected \
	before \
	second-head

normal --select-head --no-reduce first second

also_interactive hh
