#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} head" \
	head \
	"${PARENT} 2" \
	second \
	"${PARENT} 3" \
	third \
	"${PARENT} 4" \
	fourth \
	"${TAIL}" \
	tail \
	"${END} tail"

printf '%s\n' > file.expected \
	head

normal --select-head --no-reduce file

also_interactive h
