#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} head" \
	head \
	"${TAIL}" \
	tail \
	"${END} tail"

printf '%s\n' > file.expected \
	head

normal --select-head --no-reduce file

also_interactive h
