#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	"${PARENT} base" \
	base \
	"${TAIL} theirs" \
	theirs \
	"${END} end of conflict"

: > file.expected

normal --select-head --no-reduce file

also_interactive h
