#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	1 \
	"${PARENT} 2" \
	1 \
	"${TAIL}" \
	"${END} theirs"

cp -- file file.expected

conflict --symmetric --no-reduce file

also_interactive y
