#!/bin/sh -e
. t/common.sh

printf '%s\n' > file \
	"${HEAD} ours" \
	new \
	new \
	"${PARENT} 2" \
	old \
	old \
	"${PARENT} 3" \
	old \
	old \
	"${TAIL}" \
	new \
	new \
	"${END} theirs"

printf '%s\n' > file.expected \
	new \
	new

normal --symmetric --no-reduce file

also_interactive y
